### ISSUE TITLE
UTF-8 not being stored correctly

### ISSUE THREAD

**Issue by jonphipps** [jonphipps/Metadata-Registry#10]
UTF-8 is being double-encoded in the database. This isn't an issue for the current OMR, since it's handled throughout. But it affects other uses of the database, like the api and future updates.

There needs to be a change to the global propel config to change to mysqli driver and add the global encoding:
```yaml
all:
  propel:
    class:                sfPropelDatabase
    param:
      phptype:            mysqli <--
      host:               localhost
      database:           swregistry
      username:           homestead
      password:           secret
      compat_assoc_lower: true
      datasource:         propel
      encoding:           UTF8 <--
```
...and then we need to ensure that all of the strings in the DB are re-encoded as single-encoded utf-8 before moving the data into the next release.

If we want to use that data with the current OMR, all of the instances in the code that decode the double-encoded uff-8 will have to be tracked down and changed.

One significant side-effect of making that change is that data moving in and out of the OMR database is currently encoded by the database as 8859-1 and would then automatically be encoded as utf-8. I unfortunately thought that setting the default on the database would do this, but apparently the database connection has to be set too, and it never has been.

So this change can't be made on the active database connection.

**Comment by jonphipps** [comment]
So... it's pretty bad but fixable: see http://melp.nl/2011/01/about-mysql-utf-8-and-saving-headaches/

There are 2 steps (this has to be done for the sandbox too):
Convert the tables that contain utf8 and the utf8 columns to the correct encoding:
```sql
ALTER TABLE foo CONVERT TO CHARACTER SET latin1;
ALTER TABLE foo modify object blob;
ALTER TABLE foo modify object text CHARSET utf8;
```
Then set the connection to mysql and utf8:
```yaml
all:
  propel:
    class:                sfPropelDatabase
    param:
      phptype:            mysqli
...
      encoding:           UTF8
```
